In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [ ]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get dimension (basically the number of levels of nesting)
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
# Get shape (no of rows and columns)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
# Get type
a.dtype

# Get size
a.itemsize

# Get total size
a.size * a.itemsize
a.nbytes

12

In [ ]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r,c]
print(c[0,5])
# Get a specific row
print(c[0,:])

6
[1 2 3 4 5 6 7]


In [ ]:
print(c[0,1:7:2])

[2 4 6]


**initializing different types of arrays**


In [ ]:
np.zeros((2,3)) # All 0s matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2)) # All 1s matrix

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
np.full((2,2),99) # Any other number
np.full(a.shape,4)

array([4, 4, 4])

In [ ]:
# Random decimal numbers
np.random.rand(4,2)
np.random.random_sample(a.shape)

array([0.83561921, 0.03588713, 0.56853994])

In [ ]:
#Random integer values
np.random.randint(7,size=(3,3))

array([[0, 3, 6],
       [6, 4, 0],
       [4, 6, 4]])

In [ ]:
np.identity(3) # only one parameter can be passed cause identity matrix is a square matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0) #0th axis is row, 1st axis is column
r2=np.repeat(arr,3,axis=1)
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [ ]:
arr1=np.ones((5,5))
arr2=np.zeros((3,3))
arr2[1,1]=9
arr1[1:4,1:4]=arr2
print(arr1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**copying arrays**

In [ ]:
m=np.array([1,2,3])
n=m # here youre creating a reference to the same array.
# so if i change n, then m also gets affected
n[0]=100
print(m)

[100   2   3]


In [ ]:
#to avoid the above situation:
o=m.copy() # here m is [100,2,3]
o[0]=99
print(m)

[100   2   3]


**mathematics**

[refer to this link to checkout what math operations are possible](http://numpy.org/doc/stable/reference/routines.math.html)

In [ ]:
a=np.array([1,2,3])
print(a+2) # does the math operation with each of the element

[3 4 5]


In [ ]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

**linear algebra**
[reference docs](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [ ]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

# a*b is not matrix multiplication. this is used to multiple each element.
# but in this case it leads to an error because the matrices are not of the same size

# so for matric multiplication you have:
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c=np.identity(3)
print(np.linalg.det(c))

1.0


**statistics**

In [ ]:
stats=np.array([[1,2,3],[4,5,6]])
np.min(stats)
np.max(stats,axis=0)
# np.sum(stats)

array([4, 5, 6])

**reorganising arrays**

In [ ]:
before=np.array([[1,2,3],[4,5,6]])
after=before.reshape((6,1)) # the new shape shuld have the same number of elements
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
# Vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving data.txt to data.txt


In [ ]:
data = np.genfromtxt('data.txt', delimiter=',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
data.astype('int32')
print(data) # this basically returns float only because in astype a copy of data is used


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
# Boolean Masking and Advanced Indexing

data>3
np.any(data>3,axis=1)
np.all(data>3,axis=0)

array([False, False, False])

In [ ]:
print(data[data>3])

[4. 5. 6. 7. 8. 9.]
